# Generated by Django 4.1.3 on 2022-12-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='academic_transcript',
            field=models.FileField(upload_to='media/acad_transcripts/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='resume',
            field=models.FileField(upload_to='media/resumes/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sop',
            field=models.FileField(upload_to='media/sops/'),
        ),
    ]
