# Generated by Django 4.1.3 on 2022-12-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0003_alter_internship_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='status',
        ),
        migrations.AlterField(
            model_name='internship',
            name='no_of_offers',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
