# Generated by Django 4.1.3 on 2023-01-21 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0012_remove_notification_recipient_notification_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=30)),
            preserve_default=False,
        ),
    ]
