# Generated by Django 4.1.3 on 2023-01-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0015_remove_internship_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='duration',
            field=models.PositiveIntegerField(default=30),
            preserve_default=False,
        ),
    ]
