# Generated by Django 4.1.3 on 2023-01-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0018_internship_application_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='application_deadline',
            field=models.DateField(),
        ),
    ]
