# Generated by Django 4.1.3 on 2023-01-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0019_alter_internship_application_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='application_deadline',
        ),
    ]
