# Generated by Django 4.1.3 on 2023-01-21 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_student_sop'),
        ('internships', '0021_internship_application_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='applied_students',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='shortlisted_students',
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_of_purpose', models.TextField()),
                ('is_shortlisted', models.BooleanField(default=False)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internships.internship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
    ]
