# Generated by Django 4.1.3 on 2023-01-30 13:16

from django.db import migrations, models
import internships.models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0023_remove_internship_duration_internship_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='statement_of_purpose',
            field=models.FileField(upload_to=internships.models.Application.sop_upload_path),
        ),
        migrations.AlterField(
            model_name='internship',
            name='eligible_departments',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AM', 'Applied Mechanics'), ('BB', 'Biochemical Engineering and Biotechnology'), ('CH', 'Chemical Engineering'), ('CS', 'Computer Science and Engineering'), ('CE', 'Civil Engineering'), ('DD', 'Design'), ('EE', 'Electrical Engineering'), ('ES', 'Energy Engineering'), ('MS', 'Materials Engineering'), ('MT', 'Mathematics and Computing'), ('ME', 'Mechanical Engineering'), ('PH', 'Engineering Physics'), ('TT', 'Textile Technology')], default=['AM', 'BB', 'CH', 'CS', 'CE', 'DD', 'EE', 'ES', 'MS', 'MT', 'ME', 'PH', 'TT'], max_length=255),
        ),
    ]
