# Generated by Django 4.1.3 on 2023-01-04 16:17

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_student_academic_transcript_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='academic_transcript',
            field=models.FileField(upload_to=users.models.Student.academic_transcript_upload_path),
        ),
        migrations.AlterField(
            model_name='student',
            name='resume',
            field=models.FileField(upload_to=users.models.Student.resume_upload_path),
        ),
        migrations.AlterField(
            model_name='student',
            name='sop',
            field=models.FileField(),
        ),
    ]
