# Generated by Django 4.1.3 on 2023-01-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_student_academic_transcript_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sop',
        ),
    ]
