# Generated by Django 4.1.3 on 2022-12-10 10:54

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('field', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('no_of_offers', models.IntegerField(default=1)),
                ('stipend', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('ONSITE', 'Onsite'), ('REMOTE', 'Remote'), ('HYBRID', 'Hybrid')], default='ONSITE', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('eligible_departments', multiselectfield.db.fields.MultiSelectField(choices=[('AM', 'Applied Mechanics'), ('BB', 'Biochemical Engineering and Biotechnology'), ('CH', 'Chemical Engineering'), ('CS', 'Computer Science and Engineering'), ('CE', 'Civil Engineering'), ('DD', 'Design'), ('EE', 'Electrical Engineering'), ('ES', 'Energy Engineering'), ('MS', 'Materials Engineering'), ('MT', 'Mathematics and Computing'), ('ME', 'Mechanical Engineering'), ('PH', 'Engineering Physics'), ('TT', 'Textile Technology')], max_length=2)),
                ('min_cgpa', models.DecimalField(decimal_places=3, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('applied_students', models.ManyToManyField(related_name='internships_applied', to='users.student')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.professor')),
                ('selected_students', models.ManyToManyField(related_name='internships_selected', to='users.student')),
                ('shortlisted_students', models.ManyToManyField(related_name='internships_shortlisted', to='users.student')),
            ],
        ),
    ]
