# Generated by Django 4.1.3 on 2022-12-26 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0006_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='start_date',
        ),
    ]
