# Generated by Django 4.1.3 on 2022-12-29 15:27

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0008_remove_internship_selected_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='eligible_departments',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AM', 'Am'), ('BB', 'Bb'), ('CH', 'Ch'), ('CS', 'Cs'), ('CE', 'Ce'), ('DD', 'Dd'), ('EE', 'Ee'), ('ES', 'Es'), ('MS', 'Ms'), ('MT', 'Mt'), ('ME', 'Me'), ('PH', 'Ph'), ('TT', 'Tt')], default=['AM', 'BB', 'CH', 'CS', 'CE', 'DD', 'EE', 'ES', 'MS', 'MT', 'ME', 'PH', 'TT'], max_length=2),
        ),
    ]
