# Generated by Django 4.1.3 on 2022-12-29 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0010_alter_internship_eligible_departments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='recepient',
            new_name='recipient',
        ),
    ]
