# Generated by Django 4.1.3 on 2023-01-04 09:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("internships", "0011_rename_recepient_notification_recipient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="recipient",
        ),
        migrations.AddField(
            model_name="notification",
            name="recipient",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
