# Generated by Django 4.1.3 on 2023-01-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0013_internship_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='duration',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
