# Generated by Django 4.1.3 on 2023-01-21 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0014_alter_internship_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='duration',
        ),
    ]
