# Generated by Django 4.1.3 on 2023-01-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0016_internship_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='expected_skills',
            field=models.TextField(default=''),
        ),
    ]
