# Generated by Django 4.1.3 on 2023-01-21 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0017_internship_expected_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='application_deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 10, 43, 44, 82450, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
