# Generated by Django 4.1.3 on 2023-01-21 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0020_remove_internship_application_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='application_deadline',
            field=models.DateField(default=datetime.datetime(2023, 2, 20, 10, 54, 34, 521902, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
