# Generated by Django 4.1.3 on 2023-01-21 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0022_remove_internship_applied_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='duration',
        ),
        migrations.AddField(
            model_name='internship',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 21, 15, 0, 36, 814175, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internship',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 22, 15, 0, 47, 719261, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
