# Generated by Django 4.1.3 on 2023-01-30 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0024_alter_application_statement_of_purpose_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
    ]
